repos:
- repo: https://github.com/psf/black
  rev: 23.3.0
  hooks:
    # - id: black
    - id: black-jupyter

- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.0.277
  hooks:
  - id: ruff

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-added-large-files
  - id: check-merge-conflict
  - id: check-toml
  - id: check-yaml
  - id: mixed-line-ending
  - id: trailing-whitespace
  - id: end-of-file-fixer

- repo: https://github.com/nbQA-dev/nbQA
  rev: 1.7.0
  # Pinning hook dependencies' versions for reproducibility, but requires manual
  # updating as a result. (cf. https://nbqa.readthedocs.io/en/latest/pre-commit.html)
  hooks:
  - id: nbqa-ruff
    additional_dependencies: ["ruff==0.0.277"]

- repo: local
  hooks:
    - id: watermark
      name: Check notebooks have watermark
      description: >-
        Jupyter notebooks should have a cell for watermark (cf. Jupyter style guide from
        CONTRIBUTING.md)
      args: ["--negate", "--multiline"]
      entry: "%load_ext watermark.*\
        %watermark --updated --date --python --iversions"
      language: pygrep
      types: [jupyter]
